# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ABTOOLS.MSGtoPDFConverter
PackageVersion: 1.0.0
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: MSG to PDF Converter\MSG to PDF Converter.exe
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.getabtools.com/releases/msg-to-pdf/1.0.0/MSG%20to%20PDF%20Converter.zip
  InstallerSha256: 1943C7BE5E1598EAF42597A2C50DABB96B238F296CB3C91EF442D67DE6C9E4F6
ManifestType: installer
ManifestVersion: 1.12.0
